### ISSUE TITLE
NE on K8s: ensure NuvlaEdge update management action works

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/deployment#100]
- [x] investigate
- [x] #112
- [x] propose a solution
- [x] implement

**Comment by giovannibianco** [comment]
Discussed with @schaubl and agree that going with a kubernetes Job with container with helm is the way to go.
will be cleaner for job-engine.
Will add helm to the nuvlaedge container so we can use this rather than the alpine/helm above.
Will link the PR.
