### ISSUE TITLE
NE on K8s: check NuvlaEdge clustering management action is relevant or else disable it

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/deployment#102]
- [x] investigate the relevancy of the clustering mgmt action for NE on K8s
  ~- if relevant, propose implementation~
  - otherwise, disable it on UI

**Comment by giovannibianco** [comment]
These clustering actions:
* Join as worker
* Join as manager
* Leave
* Force new cluster

In the Kubernetes (generically k8s) sense, these are equivalent to, respectively:
* Join Kubernetes cluster as worker node
* Join Kubernetes cluster as another master node
* Obvious
* Not sure... whole new kubernetes cluster? 

At the moment, we are making the assumption that the node that the NuvlaEdge is deployed on is the master (control-plane is True) and the deployments are also to land on that (master) node.

If we require that the k8s cluster is larger... i.e. worker nodes attached, these don't need to know anything about Nuvla... the k8s control (master) node will take care of everything.

So I don't see a need for these clustering actions from the k8s point of view.

Demo to show this might be useful?

**Comment by konstan** [comment]
After a discussion with @schaubl on the current usage of the clustering feature in Nuvla, we agreed that for now, we don't need clustering for K8s-based NEs. Hence, the follow-up decision is to disable the action on the edge UI.
