### ISSUE TITLE
investigate the impact of the current clustering features on a k8s-based NE installation

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlaedge/deployment#56]
atm, the NE v2.0 offers clustering features: join (as both manager or worker), leave, and force-new-cluster.

The architecture works in such a way that each edge device comprises an installation of the NE, and then from the UI, one can perform these clustering actions on any NE resource.

For Swarm, this works well since all NE components are deployed as standalone containers. However, in k8s, these will be deployments, pods, svcs, etc., which can be affected by a change in the cluster state.  So, is there a way for us to maintain the existing clustering features in such a way that we don't lose the NB whenever a join/leave occurs in k8s?

**Comment by konstan** [comment]
Drained/evicted nodes are still running kubelets. kubelet can work in an independent mode by starting/updating pods that are dropped to / updated in /etc/kubernetes/manifests/. This is somewhat similar to a node with a docker daemon in a non-swarm mode. We can explore that further.
I definitely need to better understand the currently available set of features with NBE on docker and hence, what is desirable for k8s.
Look at how OpenYurt does leave/join with their tooling in the examples here https://openyurt.io/en-us/docs/tutorial/yurtctl.html

**Comment by konstan** [comment]
Just a side note. I think it would be great to have `nbectl` CLI, with which one would be able to manage the NBEs (clusters).

**Comment by konstan** [comment]
Closing. The topic on clustering will be followed up in the following Epic [Revisit NuvlaEdge clustering feature](https://github.com/SixSq/tasklist/issues/2625).
